export enum FormDataFields {
    ProtocolId = 'ProtocolId',
    FirstName = 'FirstName',
    SecondName = 'SecondName',
    ThirdName = 'ThirdName',
    RandomState = 'RandomState',
    RandomNumber = 'RandomNumber',
    Pediculosis = 'Pediculosis',
    Scabies = 'Scabies',
    Tbs = 'TBS',
    Hepatitis = 'Hepatitis',
    VenerealDisease = 'VenerealDisease',
    CreateDate = 'CreateDate',
    Sex = 'Sex',
    BirthDate = 'BirthDate',
    Subject = 'Subject',
    District = 'District',
    City = 'City',
    Community = 'Community',
    Street = 'Street',
    House = 'House',
    Flat = 'Flat',
    Phone = 'Phone',
    Phones = 'Phones',
    Locality = 'Locality',
    ChISeries = 'CHIseries',
    ChINumber = 'CHInumber',
    Snils = 'SNILS',
    InsuranceMedicalOrganization = 'InsuranceMedicalOrganization',
    BenefitCategoryCode = 'BenefitCategoryCode',
    DocumentName = 'DocumentName',
    DocumentSeries = 'DocumentSeries',
    DocumentNumber = 'DocumentNumber',
    Family = 'Family',
    Education = 'Education',
    Work = 'Work',
    DisabilityType = 'DisabilityType',
    DisabilityGroup = 'DisabilityGroup',
    DisabilityDate = 'DisabilityDate',
    WorkPlace = 'WorkPlace',
    WorkPosition = 'WorkPosition',
    WorkPlaceChange = 'WorkPlaceChange',
    RegistrationPlaceChange = 'RegistrationPlaceChange',
    BloodGroup = 'BloodGroup',
    RhFactor = 'RhFactor',
    AllergicReactions = 'AllergicReactions',
    CheckupDate = 'CheckupDate',
    CheckupLocation = 'CheckupLocation',
    Doctor = 'Doctor',
    Race = 'Race',
    OtherRace = 'OtherRace',
    PatientDate = 'PatientDate',
    PatientDiagnosis = 'PatientDiagnosis',
    PatientPath = 'PatientPath',
    InternalId = 'InternalId',
    Insurance = 'Insurance',
    Syphilis = 'Syphilis',
    Screening = 'Screening',
    Deseases = 'Deseases',
    Diagnosis = 'Diagnosis',
}

export enum DiseaseData {
    Date = 'Date',
    EndDate = 'EndDate',
    Diagnosis = 'Diagnosis',
    Code = 'Code',
    Doctor = 'Doctor',
}

export enum DiagnosisData {
    Date = 'Date',
    Text = 'Text',
    Type = 'Type',
    Doctor = 'Doctor',
}

export enum PhonesData {
    Phone = 'Phone',
    Comment = 'Comment',
}

export enum InsuranceData {
    Name = 'Name',
    Id = 'Id',
}

export enum CardSyphilisData {
    DecreasedVision = 'DecreasedVision',
    DecreasedHearing = 'DecreasedHearing',
    DecreasedMemory = 'DecreasedMemory',
    Incoordination = 'Incoordination',
    HairAllopecia = 'HairAllopecia',
    HairPapula = 'HairPapula',
    HairPustula = 'HairPustula',
    HairCrust = 'HairCrust',
    TongueSpots = 'TongueSpots',
    TonguePapula = 'TonguePapula',
    TongueErosion = 'TongueErosion',
    TongueUlcers = 'TongueUlcers',
    TongueAngina = 'TongueAngina',
    TongueTonsils = 'TongueTonsils',
    LipsPapula = 'LipsPapula',
    LipsJammed = 'LipsJammed',
    LipsErosion = 'LipsErosion',
    VoiceHoarseness = 'VoiceHoarseness',
    CervicalLymph = 'CervicalLymph',
    SubmandibularLymph = 'SubmandibularLymph',
    AxillaryLymph = 'AxillaryLymph',
    ElbowLymph = 'ElbowLymph',
    InguinalLymph = 'InguinalLymph',
    BoneSaddleNose = 'BoneSaddleNose',
    BoneHighGothicPalate = 'BoneHighGothicPalate',
    BoneHutchinsonTeeth = 'BoneHutchinsonTeeth',
    BoneXiphoidProcess = 'BoneXiphoidProcess',
    BoneSaberTibia = 'BoneSaberTibia',
    GenitaliaSpots = 'GenitaliaSpots',
    GenitaliaPapula = 'GenitaliaPapula',
    GenitaliaErosion = 'GenitaliaErosion',
    GenitaliaUlcers = 'GenitaliaUlcers',
    CardId = 'CardId',
}

export enum CardScreeningData {
    DateTime = 'DateTime',
    Agreed = 'Agreed',
    FormTime = 'FormTime',
    Form = 'Form',
    FormEnoughTime = 'FormEnoughTime',
    Acquaintance = 'Acquaintance',
    Understanding = 'Understanding',
    Requirements = 'Requirements',
    Questions = 'Questions',
    FullInfo = 'FullInfo',
    FullAgreed = 'FullAgreed',
    ComplyWithTheRequirements = 'ComplyWithTheRequirements',
    Contraception = 'Contraception',
    Signed2ExamplesDateTime = 'Signed2ExamplesDateTime',
    Signed2Examples = 'Signed2Examples',
    ExampleInDocumentation = 'ExampleInDocumentation',
    Stacionar = 'Stacionar',
    SignedForm = 'SignedForm',
    AgreementOperator = 'AgreementOperator',
    IndividualString = 'IndividualString',
    HandedPolis = 'HandedPolis',
    PolisCopy = 'PolisCopy',
    Insurance = 'Insurance',
    FirstTime = 'FirstTime',
    SecondTime = 'SecondTime',
    ThirdTime = 'ThirdTime',
    CardId = 'CardId',
}

export enum CardPhysicalData {
    IsCompleted = 'IsCompleted',
    IsNorm = 'IsNorm',
    IsDeviation = 'IsDeviation',
    Comment = 'Comment',
    System = 'System',
}

export enum CardDayData {
    PhysicalExaminationTable = 'PhysicalExaminationTable',
    DayNumber = 'DayNumber',
    Date = 'Date',
    Complaints = 'Complaints',
    SystolicPressure = 'SystolicPressure',
    DiastolicPressure = 'DiastolicPressure',
    HeartRate = 'HeartRate',
    RespiratoryRate = 'RespiratoryRate',
    Temperature = 'Temperature',
    IsBloodDrawn = 'IsBloodDrawn',
    BloodDrawnTime = 'BloodDrawnTime',
    IsUrinalysisPerformedForDrugs = 'IsUrinalysisPerformedForDrugs',
    IsUrineContainsDrugs = 'IsUrineContainsDrugs',
    IsUrinalysisPerformedForCotinine = 'IsUrinalysisPerformedForCotinine',
    IsUrineContainsCotinine = 'IsUrineContainsCotinine',
    IsAlhocolContentTestPerformed = 'IsAlhocolContentTestPerformed',
    Promille = 'Promille',
    IsAdverseEvents = 'IsAdverseEvents',
    AdverseEventsDescription = 'AdverseEventsDescription',
    DoctorDecision = 'DoctorDecision',
    ConsentWithdrawal = 'ConsentWithdrawal',
    ProtocolViolation = 'ProtocolViolation',
    ParticipantInclusionViolation = 'ParticipantInclusionViolation',
    MedicationUse = 'MedicationUse',
    HospitalizationRequired = 'HospitalizationRequired',
    AdverseEvent = 'AdverseEvent',
    PositiveAlcoholBreathTest = 'PositiveAlcoholBreathTest',
    PositiveCotinineUrineTest = 'PositiveCotinineUrineTest',
    PositiveDrugUrineTest = 'PositiveDrugUrineTest',
    DehydrationBeforePeriods = 'DehydrationBeforePeriods',
    VomitingOrDiarrheaAfterDose = 'VomitingOrDiarrheaAfterDose',
    TechnicalBloodSamplingDifficulties = 'TechnicalBloodSamplingDifficulties',
    Comments = 'Comments',
    IsContinue = 'IsContinue',
    IsInvited = 'IsInvited',
    Doctor = 'Doctor',
    Id = 'Id',
    CardId = 'CardId',
}

export enum AnamnesisFields {
    Anamnesis = 'Anamnesis',
    MedicalAnamnesis = 'MedicalAnamnesis',
    PharmacologicalAnamnesis = 'PharmacologicalAnamnesis',
    FoodAllergies = 'FoodAllergies',
    FoodAllergiesString = 'FoodAllergiesString',
    DrugAllergies = 'DrugAllergies',
    DrugAllergiesString = 'DrugAllergiesString',
    AllergyType = 'AllergyType',
    Heredity = 'Heredity',
    PastIllnesses = 'PastIllnesses',
    AccompanyingIllnesses = 'AccompanyingIllnesses',
    SurgicalInterventions = 'SurgicalInterventions',
    TobaccoSmoking = 'TobaccoSmoking',
    TobaccoDailyPack = 'TobaccoDailyPack',
    Alcohol = 'Alcohol',
    AlcoholAgeRange = 'AlcoholAgeRange',
    AlcoholLastDate = 'AlcoholLastDate',
    AlcoholOnceAmount = 'AlcoholOnceAmount',
    AlcoholWeekAmount = 'AlcoholWeekAmount',
    Narcotics = 'Narcotics',
    NarcoticsLastDate = 'NarcoticsLastDate',
    NarcoticsCurrent = 'NarcoticsCurrent',
    AddictionAbuse = 'AddictionAbuse',
    Past90Days = 'Past90Days',
    CardId = 'CardId',
}

export enum AllergyType {
    AnaphylacticShock = 0,
    Angioedema = 1,
    Hives = 2,
}

export enum InsuranceOrganisationData {
    Name = 'name',
    Id = 'id',
}

export enum PhysicalExamData {
    Weight = 'Weight',
    WeightMeasurement = 'WeightMeasurement',
    Height = 'Height',

    SystolicPressure = 'SystolicPressure',
    DiastolicPressure = 'DiastolicPressure',
    HeartRate = 'HeartRate',
    RespiratoryRate = 'RespiratoryRate',
    Temperature = 'Temperature',
    Complaints = 'Complaints',

    InspectionComplete = 'InspectionComplete',
    InspectionDeviation = 'InspectionDeviation',
    InspectionIndicator = 'InspectionIndicator',
    InspectionComment = 'InspectionComment',

    SkinComplete = 'SkinComplete',
    SkinDeviation = 'SkinDeviation',
    SkinIndicator = 'SkinIndicator',
    SkinComment = 'SkinComment',

    MucousComplete = 'MucousComplete',
    MucousDeviation = 'MucousDeviation',
    MucousIndicator = 'MucousIndicator',
    MucousComment = 'MucousComment',

    LymphComplete = 'LymphComplete',
    LymphDeviation = 'LymphDeviation',
    LymphIndicator = 'LymphIndicator',
    LymphComment = 'LymphComment',

    EyesEarsNoseComplete = 'EyesEarsNoseComplete',
    EyesEarsNoseDeviation = 'EyesEarsNoseDeviation',
    EyesEarsNoseIndicator = 'EyesEarsNoseIndicator',
    EyesEarsNoseComment = 'EyesEarsNoseComment',

    HeadNeckComplete = 'HeadNeckComplete',
    HeadNeckDeviation = 'HeadNeckDeviation',
    HeadNeckIndicator = 'HeadNeckIndicator',
    HeadNeckComment = 'HeadNeckComment',

    UpperVeinsComplete = 'UpperVeinsComplete',
    UpperVeinsDeviation = 'UpperVeinsDeviation',
    UpperVeinsIndicator = 'UpperVeinsIndicator',
    UpperVeinsComment = 'UpperVeinsComment',

    CardiovascularComplete = 'CardiovascularComplete',
    CardiovascularDeviation = 'CardiovascularDeviation',
    CardiovascularIndicator = 'CardiovascularIndicator',
    CardiovascularComment = 'CardiovascularComment',

    RespiratoryComplete = 'RespiratoryComplete',
    RespiratoryDeviation = 'RespiratoryDeviation',
    RespiratoryIndicator = 'RespiratoryIndicator',
    RespiratoryComment = 'RespiratoryComment',

    MusculoskeletalComplete = 'MusculoskeletalComplete',
    MusculoskeletalDeviation = 'MusculoskeletalDeviation',
    MusculoskeletalIndicator = 'MusculoskeletalIndicator',
    MusculoskeletalComment = 'MusculoskeletalComment',

    DigestiveComplete = 'DigestiveComplete',
    DigestiveDeviation = 'DigestiveDeviation',
    DigestiveIndicator = 'DigestiveIndicator',
    DigestiveComment = 'DigestiveComment',

    UrinaryComplete = 'UrinaryComplete',
    UrinaryDeviation = 'UrinaryDeviation',
    UrinaryIndicator = 'UrinaryIndicator',
    UrinaryComment = 'UrinaryComment',

    NervousComplete = 'NervousComplete',
    NervousDeviation = 'NervousDeviation',
    NervousIndicator = 'NervousIndicator',
    NervousComment = 'NervousComment',

    MentalComplete = 'MentalComplete',
    MentalDeviation = 'MentalDeviation',
    MentalIndicator = 'MentalIndicator',
    MentalComment = 'MentalComment',

    ECGTaken = 'ECGTaken',
    ECGTapeAttached = 'ECGTapeAttached',
    ECGComment = 'ECGComment',

    UrineAnalysis = 'UrineAnalysis',
    UrineAnalysisName = 'UrineAnalysisName',
    UrineAnalysisResult = 'UrineAnalysisResult',
    UrineKotininAnalysis = 'UrineKotininAnalysis',
    UrineKotininAnalysisResult = 'UrineKotininAnalysisResult',
    AlcoholTestPromiles = 'AlcoholTestPromiles',
    PregnancyTest = 'PregnancyTest',
    PregnancyTestResult = 'PregnancyTestResult',
    CovidTest = 'CovidTest',
    CovidTestResult = 'CovidTestResult',

    CovidOldTest = 'CovidOldTest',
    CovidOldTestDate = 'CovidOldTestDate',
    Test10HoursAware = 'Test10HoursAware',

    LabDate = 'LabDate',
    EmptyStomach = 'EmptyStomach',
    BloodSamples = 'BloodSamples',
    BloodCentralLab = 'BloodCentralLab',
    UrineCentralLab = 'UrineCentralLab',
    LabRoute = 'LabRoute',
    LabRouteName = 'LabRouteName',
    RgSurveyRoute = 'RgSurveyRoute',
    XRay = 'XRay',
    XRayCopy = 'XRayCopy',
    Analysis = 'Analysis',
    AnalysisDate = 'AnalysisDate',

    GeneralBloodComplete = 'GeneralBloodComplete',
    GeneralBloodIndicator = 'GeneralBloodIndicator',
    GeneralBloodDeviation = 'GeneralBloodDeviation',
    GeneralBloodComment = 'GeneralBloodComment',

    BioBloodComplete = 'BioBloodComplete',
    BioBloodIndicator = 'BioBloodIndicator',
    BioBloodDeviation = 'BioBloodDeviation',
    BioBloodComment = 'BioBloodComment',

    UrinalysisSedimentComplete = 'UrinalysisSedimentComplete',
    UrinalysisSedimentIndicator = 'UrinalysisSedimentIndicator',
    UrinalysisSedimentDeviation = 'UrinalysisSedimentDeviation',
    UrinalysisSedimentComment = 'UrinalysisSedimentComment',

    HIVComplete = 'HIVComplete',
    HIVIndicator = 'HIVIndicator',
    HIVDeviation = 'HIVDeviation',
    HIVComment = 'HIVComment',
}

export enum CriteriaFields {
    IncludeCriteria1 = 'IncludeCriteria1',
    IncludeCriteria2 = 'IncludeCriteria2',
    IncludeCriteria3 = 'IncludeCriteria3',
    IncludeCriteria4 = 'IncludeCriteria4',
    IncludeCriteria5 = 'IncludeCriteria5',
    IncludeCriteria6 = 'IncludeCriteria6',
    IncludeCriteria7 = 'IncludeCriteria7',
    IncludeCriteria8 = 'IncludeCriteria8',
    IncludeCriteria9 = 'IncludeCriteria9',
    IncludeCriteria10 = 'IncludeCriteria10',
    IncludeCriteria11 = 'IncludeCriteria11',
    IncludeCriteria12 = 'IncludeCriteria12',
    IncludeCriteria13 = 'IncludeCriteria13',
    IncludeCriteria14 = 'IncludeCriteria14',
    IncludeCriteria15 = 'IncludeCriteria15',
    ExcludeCriteria1 = 'ExcludeCriteria1',
    ExcludeCriteria2 = 'ExcludeCriteria2',
    ExcludeCriteria3 = 'ExcludeCriteria3',
    ExcludeCriteria4 = 'ExcludeCriteria4',
    ExcludeCriteria5 = 'ExcludeCriteria5',
    ExcludeCriteria6 = 'ExcludeCriteria6',
    ExcludeCriteria7 = 'ExcludeCriteria7',
    ExcludeCriteria8 = 'ExcludeCriteria8',
    ExcludeCriteria9 = 'ExcludeCriteria9',
    ExcludeCriteria10 = 'ExcludeCriteria10',
    ExcludeCriteria11 = 'ExcludeCriteria11',
    ExcludeCriteria12 = 'ExcludeCriteria12',
    ExcludeCriteria13 = 'ExcludeCriteria13',
    ExcludeCriteria14 = 'ExcludeCriteria14',
    ExcludeCriteria15 = 'ExcludeCriteria15',
    ExcludeCriteria16 = 'ExcludeCriteria16',
    ExcludeCriteria17 = 'ExcludeCriteria17',
    ExcludeCriteria18 = 'ExcludeCriteria18',
    ExcludeCriteria19 = 'ExcludeCriteria19',
    ExcludeCriteria20 = 'ExcludeCriteria20',
    ExcludeCriteria21 = 'ExcludeCriteria21',
    ExcludeCriteria22 = 'ExcludeCriteria22',
    ExcludeCriteria23 = 'ExcludeCriteria23',
    ExcludeCriteria24 = 'ExcludeCriteria24',
    Comment = 'Comment',
    CriteriaEvaluated = 'CriteriaEvaluated',
    CriteriaAccepted = 'CriteriaAccepted',
    CriteriaAllowed = 'CriteriaAllowed',
    CriteriaYesNo = 'CriteriaYesNo',
    PhoneDateTime = 'PhoneDateTime',
    PhoneDate = 'PhoneDate',
    PhoneTime = 'PhoneTime',
    PhoneYesNo = 'PhoneYesNo',
    Informed = 'Informed',
    Hospitalized = 'Hospitalized',
    VisitComment = 'VisitComment',
    Doctor = 'Doctor',
    CardId = 'CardId',
}
