import { FieldType, FormConstructorModel } from '../../../form/types/types';

export const syphilisExaminationForm: FormConstructorModel = {
  entityName: 'outpatientCard',
  formEntityName: 'syphilisExaminationForm',
  cards: [
    {
      id: 'card',
      key: 'patientComplaints',
      title: 'Жалобы больного',
      columnCount: 2,
      fields: [
        {
          id: 'decreasedVision',
          title: 'Cнижение зрения',
          type: FieldType.Checkbox,
          name: 'decreasedVision',
          initialValue: false,
        },
        {
          id: 'decreasedHearing',
          title: 'Cнижение слуха',
          type: FieldType.Checkbox,
          name: 'decreasedHearing',
          initialValue: false,
        },
        {
          id: 'decreasedMemory',
          title: 'Cнижение памяти',
          type: FieldType.Checkbox,
          name: 'decreasedMemory',
          initialValue: false,
        },
        {
          id: 'incoordination',
          title: 'Нарушение координации движения',
          type: FieldType.Checkbox,
          name: 'incoordination',
          initialValue: false,
        },
      ],
    },
    {
      id: 'card',
      key: 'externalInspection',
      title: 'Наружный осмотр В/ч головы: наличие',
      columnCount: 2,
      fields: [
        {
          id: 'hairAllopecia',
          title: 'аллопеций',
          type: FieldType.Checkbox,
          name: 'hairAllopecia',
          initialValue: false,
        },
        {
          id: 'hairPapula',
          title: 'папулы',
          type: FieldType.Checkbox,
          name: 'hairPapula',
          initialValue: false,
        },
        {
          id: 'hairPustula',
          title: 'пустулы',
          type: FieldType.Checkbox,
          name: 'hairPustula',
          initialValue: false,
        },
        {
          id: 'hairCrust',
          title: 'корочки',
          type: FieldType.Checkbox,
          name: 'hairCrust',
          initialValue: false,
        },
      ],
    },
    {
      id: 'card',
      key: 'tongue',
      title: 'Слизистая полости рта, язык',
      columnCount: 2,
      fields: [
        {
          id: 'tongueSpots',
          title: 'Пятна',
          type: FieldType.Checkbox,
          name: 'tongueSpots',
          initialValue: false,
        },
        {
          id: 'tonguePapula',
          title: 'Папулы',
          type: FieldType.Checkbox,
          name: 'tonguePapula',
          initialValue: false,
        },
        {
          id: 'tongueErosion',
          title: 'Эрозии',
          type: FieldType.Checkbox,
          name: 'tongueErosion',
          initialValue: false,
        },
        {
          id: 'tongueUlcers',
          title: 'Язвы',
          type: FieldType.Checkbox,
          name: 'tongueUlcers',
          initialValue: false,
        },
        {
          id: 'tongueAngina',
          title: 'Ангина',
          type: FieldType.Checkbox,
          name: 'tongueAngina',
          initialValue: false,
        },
      ],
    },
    {
      id: 'card',
      key: 'lips',
      title: 'Cостояние губ',
      columnCount: 2,
      fields: [
        {
          id: 'lipsPapula',
          title: 'Папулы',
          type: FieldType.Checkbox,
          name: 'lipsPapula',
          initialValue: false,
        },
        {
          id: 'lipsJammed',
          title: 'Заеды',
          type: FieldType.Checkbox,
          name: 'lipsJammed',
          initialValue: false,
        },
        {
          id: 'lipsErosion',
          title: 'Эрозии',
          type: FieldType.Checkbox,
          name: 'lipsErosion',
          initialValue: false,
        },
        {
          id: 'voiceHoarseness',
          title: 'Осиплость голоса',
          type: FieldType.Checkbox,
          name: 'voiceHoarseness',
          initialValue: false,
        },
      ],
    },
    {
      id: 'card',
      key: 'lymph',
      title: 'Пальпация лимфатических узлов',
      columnCount: 2,
      fields: [
        {
          id: 'сervicalLymph',
          title: 'Шейные',
          type: FieldType.Checkbox,
          name: 'сervicalLymph',
          initialValue: false,
        },
        {
          id: 'submandibularLymph',
          title: 'Подчелюстные',
          type: FieldType.Checkbox,
          name: 'submandibularLymph',
          initialValue: false,
        },
        {
          id: 'axillaryLymph',
          title: 'Подмышечные',
          type: FieldType.Checkbox,
          name: 'axillaryLymph',
          initialValue: false,
        },
        {
          id: 'elbowLymph',
          title: 'Локтевые',
          type: FieldType.Checkbox,
          name: 'elbowLymph',
          initialValue: false,
        },
        {
          id: 'inguinalLymph',
          title: 'Паховые',
          type: FieldType.Checkbox,
          name: 'inguinalLymph',
          initialValue: false,
        },
      ],
    },
    {
      id: 'card',
      key: 'bone',
      title: 'Наличие костных диструкций',
      columnCount: 2,
      fields: [
        {
          id: 'boneSaddleNose',
          title: 'Седловидный нос',
          type: FieldType.Checkbox,
          name: 'boneSaddleNose',
          initialValue: false,
        },
        {
          id: 'boneHighGothicPalate',
          title: 'Высокое готическое нёбо',
          type: FieldType.Checkbox,
          name: 'boneHighGothicPalate',
          initialValue: false,
        },
        {
          id: 'boneHutchinsonTeeth',
          title: 'Зубы Гетчинсона',
          type: FieldType.Checkbox,
          name: 'boneHutchinsonTeeth',
          initialValue: false,
        },
        {
          id: 'boneXiphoidProcess',
          title: 'Отсутствие мечевидного отростка',
          type: FieldType.Checkbox,
          name: 'boneXiphoidProcess',
          initialValue: false,
        },
        {
          id: 'boneSaberTibia',
          title: 'Саблевидные голени',
          type: FieldType.Checkbox,
          name: 'boneSaberTibia',
          initialValue: false,
        },
      ],
    },
    {
      id: 'card',
      key: 'bone',
      title: 'Осмотр гениталий и перианальной области (для врачей акушеров гинекологов, урологов, проктологов)',
      columnCount: 2,
      fields: [
        {
          id: 'genitaliaSpots',
          title: 'Пятна',
          type: FieldType.Checkbox,
          name: 'genitaliaSpots',
          initialValue: false,
        },
        {
          id: 'genitaliaPapula',
          title: 'Папулы',
          type: FieldType.Checkbox,
          name: 'genitaliaPapula',
          initialValue: false,
        },
        {
          id: 'genitaliaErosion',
          title: 'Эрозии',
          type: FieldType.Checkbox,
          name: 'genitaliaErosion',
          initialValue: false,
        },
        {
          id: 'genitaliaUlcers',
          title: 'Язвы',
          type: FieldType.Checkbox,
          name: 'genitaliaUlcers',
          initialValue: false,
        },
      ],
    },
  ],
};
