name: DEPLOY_PROD
on:
  pull_request:
    branches:
      - prod
    types: [closed]
jobs:
  pipeline_pull_request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    env:
        STAND: ${{ vars.STAND_PROD }}
        PASSWORD: ${{ secrets.PROD_SERVER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Build production project
        run: npm run deploy:prod